{{- if and (eq .Values.env.authEnabled "true") (not .Values.auth.existingSecret) .Values.auth.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secretName }}
  labels:
    app.kubernetes.io/name: {{ include "gfire.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  {{ .Values.auth.secretKey }}: {{ .Values.auth.token | quote }}
{{- end }}
