{{- if and (not .Values.postgres.existingSecret) .Values.postgres.dsn }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secretName }}
  labels:
    app.kubernetes.io/name: {{ include "gfire.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  {{ .Values.postgres.secretKey }}: {{ .Values.postgres.dsn | quote }}
{{- end }}
